### ISSUE TITLE
Use behind nginx reverse proxy

### ISSUE THREAD

**Issue by skollrc** [maxime1907/docker-filegator#2]
Hi,
Thanks for your docker!

I would like to use it behind an nginx proxy manager. How can deal with it? Is there some variable to allow specific proxyfied domain? 

Edit, on peut parler en français également :-)
Kind regards

**Comment by maxime1907** [comment]
Hi, there is nothing special to do to run it behind a proxy, I have this `docker-compose.yml` that I use for traefik2 if you are interested

```yaml
version: '3.7'

services:
  filerun:
    image: maxime1907/filegator:latest
    container_name: filegator
    restart: unless-stopped
    environment:
      PUID: ${DATA_PUID}
      PGID: ${DATA_PGID}
      TZ: ${TZ}
    volumes:
      - ${DATA_PATH}:/data
      - ${DOCKER_PATH}/filegator:/config
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.$SERVICE_NAME-http.entrypoints=insecure
      - traefik.http.routers.$SERVICE_NAME-http.rule=Host(`$SERVICE_NAME.$DOMAIN_NAME`)
      - traefik.http.routers.$SERVICE_NAME-http.middlewares=redirect@file
      - traefik.http.routers.$SERVICE_NAME-https.entrypoints=secure
      - traefik.http.routers.$SERVICE_NAME-https.rule=Host(`$SERVICE_NAME.$DOMAIN_NAME`)
      - traefik.http.services.$SERVICE_NAME.loadbalancer.server.port=80

networks:
  proxy:
    external: true
```
